---
# vars file for sonarqube
postgres_root_user : root
postgres_root_pass  : root@123
my_postgres_user  :  postgres
my_postgres_password  :  postgres
ansible_effective_user_id : sonar
ansible_effective_group_id : sonar
psql_sonar_username  :  sonar
psql_sonar_password  :  sonar
sonar_db_name  :  sonar
sonar_db_user  : sonar 
sonarqube_version  :  sonarqube-9.9.1.69595
psql_version  : 14
sonar_web_port : 9000
