---
# tasks file for jenkins
- name: Pull Jenkins image
  docker_image:
    name: jenkins/jenkins
    tag: lts
    source: pull
- name: Create Jenkins container
  command: sudo docker run -d --name jenkins -p 8080:8080 -p 50000:50000 -d -v jenkins_home:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock --cpus=2 --memory=2g --memory-swap=2g jenkins/jenkins:lts
- name: Fetch Jenkins password
  retries: 5
  delay: 10
  command: docker exec -u 0 jenkins cat /var/jenkins_home/secrets/initialAdminPassword
  register: jenkins_initial_password
  until: jenkins_initial_password.rc == 0

- debug:
    var: jenkins_initial_password.stdout

- name: Install Java 17 inside Jenkins container
  retries: 5
  delay: 10
  command: docker exec -u 0 jenkins bash -c "apt-get update && apt-get install -y openjdk-17-jdk"
  register: java_install_result
  until: java_install_result.rc == 0

- name: Install Docker CLI inside Jenkins container
  command: |
    docker exec -u 0 jenkins bash -c "apt-get update && apt-get install -y curl && curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh"
  register: docker_install_result
  until: docker_install_result.rc == 0

- name: Verify Java installation inside Jenkins container
  command: docker exec -u 0 jenkins java -version
  register: java_verify_result

- debug:
    var: java_verify_result.stdout
